config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root 'landings#home'
  resources :people
  resources :users
  get 'contactenos' => 'users#new', as: :contact

  devise_scope :admin do
    get 'ingresar', to: 'devise/sessions#new', as: :sign_in
    get 'recuperar_contraseña', to: 'devise/passwords#new', as: :recover_password
    get 'nueva_contraseña', to: 'devise/passwords#edit', as: :new_password
    get 'cambiar_contraseña', to: 'devise/registrations#edit', as: :change_password
  end

end

app/models/admin.rb
# encoding: utf-8
# Admin
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cemetery.rb
class Cemetery < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  filterrific(
    available_filters: [
      :search_query,
    ],
  )
  belongs_to :sector

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    terms = query.downcase.split(/\s+/)
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    num_or_conds = 2
    where(
      terms.map { |term|
        "(LOWER(people.nombres) LIKE ? OR LOWER(people.apellidos) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }

  def nombres_completos
    [nombres, apellidos].join(' ')
  end

  def nombres_completos_2
    [apellidos, nombres].join(', ')
  end

end

app/models/sector.rb
class Sector < ActiveRecord::Base
  has_many :people
  def disponible
    capacidad - people.count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
# encoding: utf-8
# ApplicationController
class ApplicationController < ActionController::Base
  layout :layout_by_resource
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def layout_by_resource
    devise_controller? ? 'authentication' : 'application'
  end
end

app/controllers/landings_controller.rb
# encoding: utf-8
# LandingsController
class LandingsController < ApplicationController
  def home
    @people = Person.all.where(fecha_fallecimiento: Time.zone.now.strftime("%Y-%m-%d")
)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:show, :index]
  # GET /people
  def index
    @filterrific = initialize_filterrific(
      Person,
      params[:filterrific],
      persistence_id: false
    ) or return
    @people = @filterrific.find.page(params[:page]).includes(:sector)
  end

  # GET /people/1
  def show
    @person = Person.find(params[:id])
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'El beneficiario fue añadido.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /people/1
  def update
    if @person.update(person_params)
      redirect_to @person, notice: 'Los datos del beneficiario fueron actualizados.'
    else
      render :edit
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'El beneficiario fue removido.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:nombres, :apellidos, :fecha_nac, :fecha_fallecimiento, :obituario, :sector_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
    @sectors = Sector.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        ExampleMailer.sample_email(@user).deliver_later
        format.html { redirect_to root_path, notice: 'Le enviamos un mensaje a su correo.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nombres, :correo, :mensaje)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/walkers_helper.rb
module WalkersHelper
end

app/views/landings/home.html.haml
%section.background
  .max-container
    .medium-container.slider
      .us
        %h3 VISIÓN
        %p Brindamos asistencias de sepelio  a las familias, acompañándolas desde nuestra fe católica, con espíritu de oración, reverencia  y esperanza en la Resurrección.
      .us
        %h3 MISIÓN
        %p Ser reconocidos como un Cementerio Católico que se preocupa por las familias y que está conformado por un grupo humano acogedor, unido y comprometido.
      .us
        %h3 IDENTIDAD CATÓLICA
        %p Somos una Institución  Católica que tiene la actividad sagrada de enterrar a las personas y de evangelizar a sus familias, brindándoles asistencias previsionales con esperanza cristiana.
%section.obituario
  = image_tag 'logo-cruz.png'
  %h2 OBITUARIO
  .obituario
    - if @people.count == 0
      %h4 No hay obituarios registrados hoy
    - else
      %table
        %thead
          %tr
            %th Datos del beneficiario
            %th Sector
        %tbody
          - @people.each do |person|
            %tr
              %td= "#{person.nombres} #{person.apellidos}"
              %td= person.sector.nombre

app/views/layouts/_header.html.haml
%header
  .max-container
    = link_to root_path do
      .logo= image_tag 'logo-white.png'
    %i.fa.fa-bars
    %nav
      %ul.no-margin.no-padding.nav
        =link_to root_path do
          %li INICIO
        =link_to people_path do
          %li BÚSQUEDA
        =link_to contact_path do
          %li CONTÁCTENOS
        - if admin_signed_in?
          %li.account CUENTA
          %ul.settings.no-padding
            = link_to change_password_path do
              %li Cambiar contraseña
            = link_to destroy_admin_session_path, method: :delete do
              %li Cerrar sesión

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Parque del Recuerdo
    %meta{:charset=>"utf-8"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", :rel => "stylesheet"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.main{"data-no-turbolink" => "true"}
    = render 'layouts/header'
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        %div{:class => "#{name} alert-message"}
          %p.no-margin<
            = msg
            %i.fa.fa-times>
    = yield

app/views/layouts/authentication.html.haml
!!!
%html{:lang=>"es"}
  %head
    %title Walkers Cemetery
    %meta{:charset=>"utf-8"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %link{:href => "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", :rel => "stylesheet"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.authentication{"data-no-turbolink" => "true"}
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        %div{:class => "#{name} alert-message"}
          %p.no-margin<
            = msg
            %i.fa.fa-times>
    = yield

app/views/people/_form.html.haml
= form_for(@person) do |f|
  - if @person.errors.any?
    #error_explanation
      %h2
        = pluralize(@person.errors.count, "error")
        prohibited this person from being saved:
      %ul
        - @person.errors.full_messages.each do |message|
          %li= message
  .walker-form
    %div
      = f.text_field :nombres, placeholder: 'Nombres', required: true, pattern: '[a-zA-Z ]*$', title: 'Introduzca su(s) nombre(s) correctamente'
    %div
      = f.text_field :apellidos, placeholder: 'Apellidos', required: true, pattern: '[a-zA-Z ]*$', title: 'Introduzca su(s) apellido(s) correctamente'
    .start-date
      = f.text_field :fecha_nac, placeholder: 'Fecha de nacimiento', required: true, class: 'datePicker', pattern: '[0-3]+[0-9]+/+[0-1][0-9]+/[0-9]{4}', title: 'Introduzca la fecha correctamente'
    .end-date
      = f.text_field :fecha_fallecimiento, placeholder: 'Fecha de defunción', required: true, class: 'datePicker', pattern: '[0-3]+[0-9]+/+[0-1][0-9]+/[0-9]{4}', title: 'Introduzca la fecha correctamente'
    %div
      = f.select :sector_id, options_from_collection_for_select(Sector.all.order(created_at: :asc), 'id', 'nombre', "#{@person.sector_id}"), { :include_blank => 'Seleccionar sector' }, :required => true
    %figure.sector= image_tag 'parque.png'
    .btn-group
      %button.btn Guardar
      = link_to 'Cancelar', people_path, class: 'btn-block btn btn-cancel'

app/views/people/_list.html.haml
#filterrific_results.results
  %table
    %tbody
      - people.each do |person|
        %tr
          %td= link_to person.nombres_completos_2, person

app/views/people/edit.html.haml
%section.max-container
  %h2 Editar datos de beneficiario
  = render 'form'

app/views/people/index.html.haml
%p#notice= notice
%section.search.max-container
  = form_for_filterrific @filterrific do |f|
    = f.text_field( :search_query, class: 'filterrific-periodically-observed', placeholder: 'Buscar por nombre o apellido' )
  = render(partial: 'people/list', locals: { people: @people.order(apellidos: :asc) })
  - if admin_signed_in?
    .new
      = link_to 'Añadir beneficiario', new_person_path, class: 'btn btn-block'

app/views/people/index.js.erb
<% js = escape_javascript(
  render(partial: 'people/list', locals: { people: @people.order(apellidos: :asc) })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/people/new.html.haml
%section.max-container
  %h2 Añadir beneficiario
  = render 'form'

app/views/people/show.html.haml
%p#notice= notice
%section.max-container
  %h2 Datos del beneficiario
  .data
    .show-data
      %h3 Nombres:
      %h3= @person.nombres_completos
    .show-data
      %h3 Fecha de nacimiento:
      %h3= @person.fecha_nac
    .show-data
      %h3 Fecha de defunción:
      %h3= @person.fecha_fallecimiento
    .show-data
      %h3 Sector:
      %h3= @person.sector.nombre
  %figure.sector= image_tag "sector-#{@person.sector.id}.png"
  - if admin_signed_in?
    .walker-form
      .btn-group
        = link_to 'Editar', edit_person_path(@person), class: 'btn-block btn'
        = link_to 'Atrás', people_path, class: 'btn-block btn btn-cancel'
      .btn-group
        = link_to 'Eliminar', @person, confirm: '¿Estás seguro?', method: :delete, class: 'btn-danger btn-block btn btn-cancel'

app/views/users/_form.html.haml
.contact-form
  = form_for(@user) do |f|
    - if @user.errors.any?
      #error_explanation
        %h2
          = pluralize(@user.errors.count, "error")
          prohibited this user from being saved:
        %ul
          - @user.errors.full_messages.each do |message|
            %li= message
    .field
      = f.text_field :nombres, placeholder: 'Nombres', required: true, pattern: '[a-zA-Z ]*$', title: 'Introduzca su(s) nombre(s) correctamente'
    .field
      = f.text_field :correo, placeholder: 'Correo electrónico', required: true
    .field
      = f.text_area :mensaje, placeholder: 'Escriba su mensaje', required: true
    %div
      %button.btn ENVIAR

app/views/users/new.html.haml
%section.contact
  %h2 Sectores del Parque del Recuerdo
  .sector= image_tag 'parque-sectorizado.png'
  %table.contact-table
    %thead
      %tr
        %th Sector
        %th Nichos disponibles
    %tbody
      - @sectors.each do |sector|
        %tr
          %td= sector.nombre
          %td= sector.disponible
  %h2 Contáctenos
  = render 'form'